#!/bin/csh

root -b -l -q 'etaR9bins_interp.C("lowR9",1,0,1)'
root -b -l -q 'etaR9bins_interp.C("midR9",1,0,1)'
root -b -l -q 'etaR9bins_interp.C("highR9",1,0,1)'
root -b -l -q 'etaR9bins_interp.C("lowR9",0,0,1)'
root -b -l -q 'etaR9bins_interp.C("midR9",0,0,1)'
root -b -l -q 'etaR9bins_interp.C("highR9",0,0,1)'

root -b -l -q 'etaR9bins_interp.C("lowR9",1,0,0)'
root -b -l -q 'etaR9bins_interp.C("midR9",1,0,0)'
root -b -l -q 'etaR9bins_interp.C("highR9",1,0,0)'
root -b -l -q 'etaR9bins_interp.C("lowR9",0,0,0)'
root -b -l -q 'etaR9bins_interp.C("midR9",0,0,0)'
root -b -l -q 'etaR9bins_interp.C("highR9",0,0,0)'

root -b -l -q 'etaR9bins_interp.C("lowR9",1,1,1)'
root -b -l -q 'etaR9bins_interp.C("midR9",1,1,1)'
root -b -l -q 'etaR9bins_interp.C("highR9",1,1,1)'
root -b -l -q 'etaR9bins_interp.C("lowR9",0,1,1)'
root -b -l -q 'etaR9bins_interp.C("midR9",0,1,1)'
root -b -l -q 'etaR9bins_interp.C("highR9",0,1,1)'

root -b -l -q 'bdtout_etaR9bins_interp.C("lowR9")'
root -b -l -q 'bdtout_etaR9bins_interp.C("mixedR9")'
root -b -l -q 'bdtout_etaR9bins_interp.C("highR9")'
root -b -l -q 'bdtout_etaR9bins_interp.C("lowR9",1)'
root -b -l -q 'bdtout_etaR9bins_interp.C("mixedR9",1)'
root -b -l -q 'bdtout_etaR9bins_interp.C("highR9",1)'

root -b -l -q 'sigmaM_etaR9bins.C(0,"lowR9")'
root -b -l -q 'sigmaM_etaR9bins.C(0,"mixedR9")'
root -b -l -q 'sigmaM_etaR9bins.C(0,"highR9")'
root -b -l -q 'sigmaM_etaR9bins.C(0,"lowR9",1)'
root -b -l -q 'sigmaM_etaR9bins.C(0,"mixedR9",1)'
root -b -l -q 'sigmaM_etaR9bins.C(0,"highR9",1)'

root -b -l -q 'sigmaM_etaR9bins.C(1,"lowR9")'
root -b -l -q 'sigmaM_etaR9bins.C(1,"mixedR9")'
root -b -l -q 'sigmaM_etaR9bins.C(1,"highR9")'
root -b -l -q 'sigmaM_etaR9bins.C(1,"lowR9",1)'
root -b -l -q 'sigmaM_etaR9bins.C(1,"mixedR9",1)'
root -b -l -q 'sigmaM_etaR9bins.C(1,"highR9",1)'
