#!/bin/bash

# set -x

packs=""
get_tag()
{
	tag=$1 && shift
	src=$1 && shift
	dst=$src
	[[ -n $1 ]] && dst=$1 && shift
	
	if [[ -d $dst ]]; then
		cvs up -r $tag $dst
	else
		cvs co -r $tag -d $dst $src
	fi
	packs="$packs $dst"
}

cd $CMSSW_BASE/src
get_tag V00-02-05 UserCode/CMG/CMGTools/External CMGTools/External 

if [[ -n $packs ]]; then 
    scram b -j 10 $packs
fi

