#!/bin/bash

# set -x
H2GGLOBE_BASE=${PWD}

packs=""
get_tag()
{
	tag=$1 && shift
	src=$1 && shift
	dst=$src
	[[ -n $1 ]] && dst=$1 && shift
	
	if [[ -d $dst ]]; then
		cvs up -r $tag $dst
	else
		cvs co -r $tag -d $dst $src
	fi
	packs="$packs $dst"
}

cd $CMSSW_BASE/src
get_tag V00-02-10 UserCode/CMG/CMGTools/External CMGTools/External 
if [[ -n $packs ]]; then 
    scram b $packs
fi

# Regression (need to adapt get_tag for github)
if [[ ! -d HiggsAnalysis/GBRLikelihood  ]]; then
 if [[ $CMSSW_VERSION == CMSSW_6_* ]]; then 
  git clone -b hggpapertraining https://github.com/bendavid/GBRLikelihood.git HiggsAnalysis/GBRLikelihood
  else git clone -b hggpaperV5 https://github.com/bendavid/GBRLikelihood.git HiggsAnalysis/GBRLikelihood
 fi
fi 
cd HiggsAnalysis/GBRLikelihood
scram b
cd $CMSSW_BASE/src

if [[ ! -d HiggsAnalysis/CombinedLimit ]]; then
  git clone https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit.git HiggsAnalysis/CombinedLimit
fi
cd HiggsAnalysis/CombinedLimit
scram b

cd ${H2GGLOBE_BASE}
touch .extraTags
